FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y doxygen graphviz

WORKDIR /docs-generator

COPY src/main/resources/Doxyfile .

RUN mkdir -p /docs-output && chmod -R a+rwx /docs-output

CMD ["sh", "-c", "doxygen Doxyfile && cp -r out/html/* /docs-output/"]
