FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y doxygen graphviz git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /doxygen

COPY src/main/resources/Doxyfile .
COPY src/main/java /src

VOLUME /output

CMD ["doxygen", "Doxyfile"]
