FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y doxygen graphviz git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /doxygen

COPY src/main/resources/Doxyfile .
COPY src/main/java /src

RUN mkdir -p /output && \
    chmod -R 777 /output && \
    echo "=== Archivos fuente ===" && \
    ls -lR /src && \
    doxygen Doxyfile 2>&1 | tee doxygen.log && \
    echo "=== Resultado generado ===" && \
    ls -lR /output/html
