name: Auto Doxygen Documentation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Doxygen dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate documentation
        run: |
          mvn doxygen:generate
          # Copia los archivos generados a la carpeta docs
          mkdir -p docs
          cp -r target/doxygen/html/* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doxygen/html
          keep_files: false
          force_orphan: true
