# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    enviroment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_ulr}}

    steps:
      # 1. Clona tu código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Prepara JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Instala Doxygen y Graphviz
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # 4. Genera el sitio y la doc
      - name: Build & Generate Site (incluye Doxygen)
        run: mvn clean site

      # 5. Copia la documentación a la carpeta docs
      - name: Copy generated docs
        run: |
          mkdir -p docs/site
          cp -r target/site/* docs/site/
          mkdir -p docs/doxygen
          cp -r target/site/doxygen/* docs/doxygen/

      # 6. Publica en GitHub Pages desde main/docs
      - name: Commit and push docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -f docs
          git commit -m "Update docs [ci skip]" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
